title: dave cox
description: > # this means to ignore newlines until "baseurl:"
  i make stuff
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davecox.ca" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: dave cox # add your name
author-img: dave.jpg # add your photo
about-author: i make stuff
twitter: unicycledave # add your Twitter handle
# facebook: # add your Facebook handle
github: unicycledave # add your Github handle
# linkedin: # add your Linkedin handle
email: dave.davecox@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
